#!/bin/bash
sudo cp /home/pi/photobooth/Photos/tmp/* /home/pi/photobooth/Photos/images
sudo mogrify -resize 565 /home/pi/photobooth/Photos/tmp/*
sleep 0.1
sudo montage /home/pi/photobooth/Photos/tmp/*.jpg /home/pi/photobooth/Photos/Template/template.png -tile 1x4 -geometry +10+10 /home/pi/photobooth/Photos/tmp/temp_montage.jpg
suffix=$(date +%d%m%Y_%H:%M:%S)
sleep 0.1
sudo cp /home/pi/photobooth/Photos/tmp/temp_montage.jpg /home/pi/photobooth/Photos/${suffix}.jpg
sleep 0.1
lp -d EPSON_Stylus_DX3800 /home/pi/photobooth/Photos/tmp/temp_montage.jpg
